PersistenceSystemConfig : "{BEFFBD9A87620F23}Configs/Systems/Persistence/BaseSetup.conf" {
 Storages {
  GamemodeStorage "{6A8AF5C32FA48FA3}" {
   Database "{6624ADA9A88DA0F6}"
  }
 }
 Collections {
  PersistenceCollection "{6A8AF5C32FA4D5F8}" {
   Name "MarxWallets"
   Storage "{6A8AF5C32FA48FA3}"
  }
  PersistenceCollection "{6A8AF5C32FA518D9}" {
   Name "MarxStashes"
   Storage "{6A8AF5C32FA48FA3}"
  }
 }
 Configurations {
  PersistenceConfigGroup ScriptedStates {
   Configurations {
    PersistenceConfigGroup Gameplay {
     Configurations {
      StatePersistenceConfig "{6A8AF5C32FA53917}" {
       Collection "{6A8AF5C32FA4D5F8}"
       Serializer MRX_WalletStateSerializer "{6A8AF5C32FA52B07}" {
       }
      }
      StatePersistenceConfig "{6A8AF5C32FA57B60}" {
       Collection "{6A8AF5C32FA518D9}"
       Serializer MRX_StashStateSerializer "{6A8AF5C32FA56D40}" {
       }
      }
     }
    }
   }
  }
 }
}