MRX_ShopCatalog {
 m_aItems {
  MRX_ShopItem "{6A8D2529438DE4FF}" {
   m_sId "stash_page"
   m_sPrefab "{06B68C58B72EAAC6}Prefabs/Items/Equipment/Backpacks/Backpack_ALICE_Medium.et"
   m_sName "#CTR-Shop_StashExpansion"
   m_sCategory "#CTR-Category_Stash"
   m_sDescription "#CTR-Shop_StashExpansionDesc"
   m_Product CTR_StashPageProduct "{6A8D2529438DE439}" {
    m_iMaxPages 8
   }
   m_iPrice 1000000
   m_iSellPrice 0
   m_iStock -1
  }
  MRX_ShopItem {
   m_sId "loadout_slot"
   m_sPrefab "{2835A0EA3B79E63E}Prefabs/Characters/Vests/Vest_ALICE/Variants/Vest_ALICE_rifleman.et"
   m_sName "#CTR-Shop_LoadoutExpansion"
   m_sCategory "#CTR-Category_Stash"
   m_sDescription "#CTR-Shop_LoadoutExpansionDesc"
   m_Product CTR_LoadoutSlotProduct {
   }
   m_iPrice 1500000
   m_iSellPrice 0
   m_iStock -1
  }
 }
}