CTR_Settings {
 m_aTaskRewards {
  CTR_TaskReward "{6A8AFD46BE65293B}" {
   m_sBuilderClass "COE_ClearAreaTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 6000
  }
  CTR_TaskReward "{6A8AFD46BE652946}" {
   m_sBuilderClass "COE_FindIntelTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 8000
  }
  CTR_TaskReward "{6A8AFD46BE652973}" {
   m_sBuilderClass "COE_DestroyCacheTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 8000
  }
  CTR_TaskReward "{6A8AFD46BE65297A}" {
   m_sBuilderClass "COE_DemineEffectModuleTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 7000
  }
  CTR_TaskReward "{6A8AFD46BE652967}" {
   m_sBuilderClass "COE_DestroyInstallationTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 10000
  }
  CTR_TaskReward "{6A8AFD46BE65296E}" {
   m_sBuilderClass "COE_DestroyVehicleTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 10000
  }
  CTR_TaskReward "{6A8AFD46BE652895}" {
   m_sBuilderClass "COE_EnemyOfficerTaskBuilder"
   m_sTaskPrefab "{DE9C612D13BF9B18}Prefabs/Tasks/KSC_TakeCaptiveTask.et"
   m_iAmount 18000
  }
  CTR_TaskReward "{6A8AFD46BE65288D}" {
   m_sBuilderClass "COE_EnemyOfficerTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 12000
  }
  CTR_TaskReward "{6A8AFD46BE6528B4}" {
   m_sBuilderClass "COE_FreeHostageTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 20000
  }
 }
 m_iDefaultTaskReward 6000
 m_iKillReward 250
 m_iTeamKillPenalty 10000
 m_iDeathPenalty 2500
 m_iFriendlyHealReward 300
 m_iCprRewardSeconds 15
 m_iCprMaxSecondsPerPatient 120
 m_iReturnDelaySeconds 30
 m_aStarterKit {
  "{E95480D14AEE3EF4}Prefabs/Characters/Uniforms/Crye_Shirt/Jacket_Crye_Combat_Shirt_Rolled_mcblack.et" "{7824F6BA0A92A8DC}Prefabs/Characters/Uniforms/Pants_FROG_Trousers_MC.et" "{057E63449502EBCA}Prefabs/Characters/Footwear/Boots_Salomon/Footwear_Salomon.et" "{1E991CD19C6F7659}Prefabs/Characters/Handwear/Gloves_MechanixMpact/Gloves_mpack_Brown.et" "{3E413771E1834D2F}Prefabs/Weapons/Rifles/M16/Rifle_M16A2.et" "{2EBF60EF24B108FC}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M855_Ball.et" "{2EBF60EF24B108FC}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M855_Ball.et" "{2EBF60EF24B108FC}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M855_Ball.et" "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et" "{A81F501D3EF6F38E}Prefabs/Items/Medicine/FieldDressing_01/FieldDressing_US_01.et" "{D70216B1B2889129}Prefabs/Items/Medicine/Tourniquet_01/Tourniquet_US_01.et" "{61D4F80E49BF9B12}Prefabs/Items/Equipment/Compass/Compass_SY183.et" "{13772C903CB5E4F7}Prefabs/Items/Equipment/Maps/Map_Paper_01/PaperMap_01_folded.et" "{D69684663E89D6EA}Prefabs/Items/Equipment/Radios/Radio_ANPRC152A_OLD.et"
 }
 m_fSafeZoneRadius 75
}