CTR_Settings {
 m_aTaskRewards {
  CTR_TaskReward "{6A8AFD46BE65293B}" {
   m_sBuilderClass "COE_ClearAreaTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 150
  }
  CTR_TaskReward "{6A8AFD46BE652946}" {
   m_sBuilderClass "COE_FindIntelTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 200
  }
  CTR_TaskReward "{6A8AFD46BE652973}" {
   m_sBuilderClass "COE_DestroyCacheTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 200
  }
  CTR_TaskReward "{6A8AFD46BE65297A}" {
   m_sBuilderClass "COE_DemineEffectModuleTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 200
  }
  CTR_TaskReward "{6A8AFD46BE652967}" {
   m_sBuilderClass "COE_DestroyInstallationTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 250
  }
  CTR_TaskReward "{6A8AFD46BE65296E}" {
   m_sBuilderClass "COE_DestroyVehicleTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 250
  }
  CTR_TaskReward "{6A8AFD46BE652895}" {
   m_sBuilderClass "COE_EnemyOfficerTaskBuilder"
   m_sTaskPrefab "{DE9C612D13BF9B18}Prefabs/Tasks/KSC_TakeCaptiveTask.et"
   m_iAmount 350
  }
  CTR_TaskReward "{6A8AFD46BE65288D}" {
   m_sBuilderClass "COE_EnemyOfficerTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 250
  }
  CTR_TaskReward "{6A8AFD46BE6528B4}" {
   m_sBuilderClass "COE_FreeHostageTaskBuilder"
   m_sTaskPrefab ""
   m_iAmount 350
  }
 }
 m_iDefaultTaskReward 150
 m_iKillReward 10
 m_iTeamKillPenalty 100
 m_iDeathPenalty 50
 m_iFriendlyHealReward 15
 m_iReturnDelaySeconds 10
}