SystemSettings : "{C50579A2EC48E8EF}Configs/Systems/MissionSystems.conf" {
 Systems {
  SCR_PersistenceSystem "{65DC893A5A752E89}" {
   Config "{120322FD25C6B8A2}Configs/Contractors/Persistence/CTR_Persistence.conf"
  }
  MRX_MarxSystem "{6A88FD9099EB0B30}" {
   m_sSettingsConfig "{BEF91A536C762118}Configs/Contractors/CTR_MarxSettings.conf"
  }
 }
}